export const AIModelsNames = [
  "EchoGPT",
  "DeepSeek V4 Pro",
  "Nemotron 3 Ultra",
  "GLM-5.2",
  "DeepSeek V4 Flash",
  "Tencent Hy3",
  "MiMo V2.5 Pro",
  "Qwen 3.7 Plus",
  "GPT-5.6 Sol",
  "Kimi K2.7 Code",
  "LongCat 2.0",
  "GLM-5.3 Flash",
  "Qwen 3.8 27B",
  "Qwen 3.7 Max",
  "Qwen 3.6 Plus",
  "Gemini 3.8 Flash",
  "Kimi K3",
  "MiniMax M3",
  "GPT-5.5",
  "GPT-5.6 Luna",
  "Grok 4.5",
  "Grok 4.6",
  "Gemini 3.7 Flash",
  "GPT-5.4",
  "DeepSeek V4 Flash Vision",
  "DeepSeek V4 Flash Fast",
  "Qwen 3.8 Flash",
  "Qwen 3.8 Max",
  "Qwen 3.8 Max 0902",
  "Muse Spark 1.2",
  "Muse Spark 1.3",
  "Muse Spark 1.3 Contributor",
  "Kimi K2.7 Code HighSpeed",
  "MiMo V2.5",
  "GLM-5.3",
  "GLM-5.2 Fast",
  "Step 3.7 Flash",
  "Step 3.5 Flash",
  "Tencent Hy4 Preview",
  "Inkling",
  "Inkling Small",
];
